FROM python:3.8.14-slim
ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED 1
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --uid 10000 -ms /bin/bash runner
# ❗️ We want to work inside the user local folder now
WORKDIR /home/runner/server
# ❗️ We swap from root to that user
USER 10000
# ❗️ We make sure that the user's files are on the path
ENV PATH="${PATH}:/home/runner/.local/bin"
COPY ./ ./
RUN pip install --no-cache-dir poetry \
  && poetry install --only main
EXPOSE 8000
ENTRYPOINT ["poetry", "run" ]
CMD ["uvicorn", "app.main:app", "--host",  "0.0.0.0" , "--port", "8000"]
